// <auto-generated />
using System;
using AccountService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260725133525_AddProfileAscents")]
    partial class AddProfileAscents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccountService.Domain.ProfileAscents.ProfileAscent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AscentDate")
                        .HasColumnType("date")
                        .HasColumnName("ascent_date");

                    b.Property<Guid>("AscentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ascent_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("AscentId")
                        .IsUnique()
                        .HasDatabaseName("ux_profile_ascents_ascent");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_profile_ascents_profile");

                    b.ToTable("profile_ascents", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_profiles_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_profiles_user_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Common.Infrastructure.Persistence.Idempotency.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("MessageId");

                    b.ToTable("processed_messages", (string)null);
                });

            modelBuilder.Entity("Common.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("longtext")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.ProfileAscents.ProfileAscent", b =>
                {
                    b.HasOne("AccountService.Domain.Profiles.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AccountService.Domain.ProfileAscents.PeakSnapshot", "Peak", b1 =>
                        {
                            b1.Property<Guid>("ProfileAscentId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("AltitudeMeters")
                                .HasColumnType("int")
                                .HasColumnName("peak_altitude_m");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("peak_name");

                            b1.Property<Guid>("PeakId")
                                .HasColumnType("char(36)")
                                .HasColumnName("peak_id");

                            b1.HasKey("ProfileAscentId");

                            b1.HasIndex("PeakId")
                                .HasDatabaseName("ix_profile_ascents_peak");

                            b1.ToTable("profile_ascents");

                            b1.WithOwner()
                                .HasForeignKey("ProfileAscentId");
                        });

                    b.Navigation("Peak")
                        .IsRequired();
                });

            modelBuilder.Entity("AccountService.Domain.Profiles.Profile", b =>
                {
                    b.OwnsOne("AccountService.Domain.Profiles.Avatar", "Avatar", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("avatar_public_id");

                            b1.Property<string>("SecureUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("avatar_url");

                            b1.HasKey("ProfileId");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("AccountService.Domain.Profiles.ProfileStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("profile_id")
                                .HasColumnType("char(36)")
                                .HasColumnName("profile_id");

                            b1.Property<int>("DistinctPeaks")
                                .HasColumnType("int")
                                .HasColumnName("distinct_peaks");

                            b1.Property<int>("HighestAltitudeMeters")
                                .HasColumnType("int")
                                .HasColumnName("highest_altitude_m");

                            b1.Property<Guid?>("HighestPeakId")
                                .HasColumnType("char(36)")
                                .HasColumnName("highest_peak_id");

                            b1.Property<string>("HighestPeakName")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("highest_peak_name");

                            b1.Property<DateTime?>("LastAscentDate")
                                .HasColumnType("date")
                                .HasColumnName("last_ascent_date");

                            b1.Property<int>("PublicDistinctPeaks")
                                .HasColumnType("int")
                                .HasColumnName("public_distinct_peaks");

                            b1.Property<int>("PublicHighestAltitudeMeters")
                                .HasColumnType("int")
                                .HasColumnName("public_highest_altitude_m");

                            b1.Property<Guid?>("PublicHighestPeakId")
                                .HasColumnType("char(36)")
                                .HasColumnName("public_highest_peak_id");

                            b1.Property<string>("PublicHighestPeakName")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("public_highest_peak_name");

                            b1.Property<DateTime?>("PublicLastAscentDate")
                                .HasColumnType("date")
                                .HasColumnName("public_last_ascent_date");

                            b1.Property<int>("PublicTotalAscents")
                                .HasColumnType("int")
                                .HasColumnName("public_total_ascents");

                            b1.Property<int>("TotalAscents")
                                .HasColumnType("int")
                                .HasColumnName("total_ascents");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .IsConcurrencyToken()
                                .HasColumnType("datetime(6)")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("profile_id");

                            b1.ToTable("profile_stats", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("profile_id");
                        });

                    b.Navigation("Avatar");

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
